# Application name
spring:
  ai:
    openai:
      api-key: AIzaSyDpbdB9PgVQNURbh8REMzZpGfZxYWL-uGc
      base-url: https://generativelanguage.googleapis.com/v1beta/openai
      chat:
        completions-path: /chat/completions
        options:
          model: gemini-2.5-flash
  datasource:
    url: jdbc:mysql://localhost:3306/insuranceassistdb01?createDatabaseIfNotExist=true&user=root&password=admin@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  application:
    name: insuranceassist

server:
    port: 9898

