# Application name
spring:
  ai:
    openai:
      api-key: AIzaSyDpbdB9PgVQNURbh8REMzZpGfZxYWL-uGc
      base-url: https://generativelanguage.googleapis.com/v1beta/openai
      chat:
        completions-path: /chat/completions
        options:
          model: gemini-2.5-flash
  application:
    name: insuranceassist

# Database configuration for in memory H2 database
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true

# Server port to 9898
server:
    port: 9898

